name: 'Setup flutter command'
description: 'Set up a specific version of the flutter command-line tools to the PATH'
author: 'takuyaohashi'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'lib/setup-flutter.js'
