name: "Main workflow"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter: [ 'latest', 'v1.9.1+hotfix.6' ]
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        flutter-version: ${{ matrix.flutter }}
        channel: 'stable'
    - name: show version
      run: flutter --version